export const SHOWPOPUP = 'POPUP/SHOWPOPUP';
export const HIDEPOPUP = 'POPUP/HIDEPOPUP';
export const ADDORDER = 'ORDER/ADDORDER';
export const REMOVEORDER = 'ORDER/REMOVEORDER';
export const CLEARORDERARRAY = 'ORDER/CLEARORDERARRAY';
export const IMPORTORDERS = 'ORDER/IMPORTORDERS';


